-- ============================================================
--  v99 : BACK-OFFICE (supervision) ET ASSISTANCE INTÉGRÉE
-- ============================================================
--  À exécuter après la v97. Transactionnel, rejouable.
--
--  1. Supervision : une fonction réservée à l'administrateur de la
--     plateforme, qui résume l'état de chaque client sans avoir à
--     « ouvrir » chacun d'eux. Elle ne renvoie que des compteurs.
--  2. Assistance : demandes et messages entre un client et la plateforme.
--     Un client suspendu peut toujours écrire à l'assistance.
--     Toutes les écritures passent par des fonctions : pas d'insertion
--     ni de modification directe depuis l'application.
-- ============================================================

begin;

do $$ begin
  if to_regprocedure('public.my_organisation_id()') is null then
    raise exception 'Exécutez d''abord migration_v97_abonnements_photos.sql.';
  end if;
end $$;

-- Numéros affichés aux clients (boutons Appeler et WhatsApp).
alter table public.plateforme_reglages add column if not exists telephone_assistance text;
alter table public.plateforme_reglages add column if not exists whatsapp_assistance text;
alter table public.plateforme_reglages add column if not exists horaires_assistance text;

-- ------------------------------------------------------------
-- 1. Supervision
-- ------------------------------------------------------------
create or replace function public.bo_supervision()
returns table (
  id bigint, nom text, formule text, statut text, abonnement_jusqu_au date, code_invitation text, created_at timestamptz,
  nb_stations bigint, stations_a_jour bigint, nb_comptes bigint, comptes_en_attente bigint,
  derniere_activite timestamptz, rappels_ouverts bigint,
  factures_impayees bigint, montant_impaye numeric, demandes_ouvertes bigint
) language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_platform_admin() then raise exception 'Réservé à l''administrateur de la plateforme.'; end if;
  return query
  select o.id, o.nom, o.formule, o.statut, o.abonnement_jusqu_au, o.code_invitation, o.created_at,
    (select count(*) from stations s where s.organisation_id = o.id),
    (select count(distinct sub.station_id) from submissions sub where sub.organisation_id = o.id and sub.report_date = current_date),
    (select count(*) from profiles p where p.organisation_id = o.id and p.approved),
    (select count(*) from profiles p where p.organisation_id = o.id and not p.approved),
    (select max(sub.created_at) from submissions sub where sub.organisation_id = o.id),
    (select count(*) from notifications n where n.organisation_id = o.id and not n.resolved),
    (select count(*) from factures f where f.organisation_id = o.id and f.statut = 'emise'),
    (select coalesce(sum(f.montant_ttc), 0) from factures f where f.organisation_id = o.id and f.statut = 'emise'),
    (select count(*) from assistance_demandes d where d.organisation_id = o.id and d.statut <> 'resolue')
  from organisations o
  order by o.nom;
end; $$;
revoke execute on function public.bo_supervision() from anon;

-- ------------------------------------------------------------
-- 2. Assistance : tables
-- ------------------------------------------------------------
create table if not exists public.assistance_demandes (
  id bigint generated by default as identity primary key,
  organisation_id bigint not null references public.organisations(id),
  station_id bigint references public.stations(id) on delete set null,
  created_by uuid not null,
  auteur_nom text,
  sujet text not null,
  statut text not null default 'ouverte' check (statut in ('ouverte', 'en_cours', 'resolue')),
  rappel_demande boolean not null default false,
  telephone_rappel text,
  non_lu_client boolean not null default false,
  non_lu_plateforme boolean not null default true,
  created_at timestamptz not null default now(),
  dernier_message_at timestamptz not null default now()
);
create index if not exists idx_assistance_demandes_org on public.assistance_demandes(organisation_id, dernier_message_at desc);

create table if not exists public.assistance_messages (
  id bigint generated by default as identity primary key,
  demande_id bigint not null references public.assistance_demandes(id) on delete cascade,
  organisation_id bigint not null references public.organisations(id),
  auteur uuid,
  auteur_nom text,
  de_plateforme boolean not null default false,
  contenu text not null,
  photo_path text,
  created_at timestamptz not null default now()
);
create index if not exists idx_assistance_messages_demande on public.assistance_messages(demande_id, created_at);

alter table public.assistance_demandes enable row level security;
alter table public.assistance_messages enable row level security;
revoke all on public.assistance_demandes, public.assistance_messages from anon, authenticated;
grant select on public.assistance_demandes, public.assistance_messages to authenticated;

-- Lecture : la plateforme voit tout. Un client voit ses propres demandes ;
-- son administrateur voit toutes celles de son entreprise.
-- (my_organisation_id et non current_org_id : un client suspendu garde l'accès.)
drop policy if exists p_assistance_demandes_sel on public.assistance_demandes;
create policy p_assistance_demandes_sel on public.assistance_demandes for select to authenticated
  using ((select public.is_platform_admin())
      or (organisation_id = (select public.my_organisation_id())
          and (created_by = auth.uid() or (select public.is_admin()))));

drop policy if exists p_assistance_messages_sel on public.assistance_messages;
create policy p_assistance_messages_sel on public.assistance_messages for select to authenticated
  using (exists (select 1 from public.assistance_demandes d where d.id = demande_id));

-- ------------------------------------------------------------
-- 3. Assistance : fonctions (seul moyen d'écrire)
-- ------------------------------------------------------------
-- Le compte peut-il intervenir sur cette demande ? Renvoie 'plateforme', 'client' ou NULL.
create or replace function public.assistance_role(p_demande bigint)
returns text language sql stable security definer set search_path = public as $$
  select case
    when public.is_platform_admin() then 'plateforme'
    when d.organisation_id = public.my_organisation_id()
         and (d.created_by = auth.uid() or public.is_admin())
         and exists (select 1 from profiles p where p.id = auth.uid() and p.approved) then 'client'
  end
  from assistance_demandes d where d.id = p_demande;
$$;
revoke execute on function public.assistance_role(bigint) from anon;

-- Ouvre une demande avec son premier message. Réservé aux comptes validés.
create or replace function public.assistance_ouvrir(p_sujet text, p_contenu text, p_station bigint default null,
                                                    p_rappel boolean default false, p_telephone text default null,
                                                    p_photo text default null)
returns public.assistance_demandes language plpgsql security definer set search_path = public as $$
declare p profiles; d assistance_demandes;
begin
  select * into p from profiles where id = auth.uid();
  if not found or not p.approved or p.organisation_id is null then
    raise exception 'Votre compte doit être validé pour contacter l''assistance.';
  end if;
  if coalesce(trim(p_sujet), '') = '' or coalesce(trim(p_contenu), '') = '' then
    raise exception 'Le sujet et le message sont obligatoires.';
  end if;
  if p_rappel and coalesce(trim(p_telephone), '') = '' then
    raise exception 'Indiquez le numéro auquel vous rappeler.';
  end if;
  if p_station is not null and not exists (select 1 from stations where id = p_station and organisation_id = p.organisation_id) then
    p_station := null;
  end if;
  insert into assistance_demandes(organisation_id, station_id, created_by, auteur_nom, sujet, rappel_demande, telephone_rappel)
  values (p.organisation_id, p_station, p.id, p.full_name, left(trim(p_sujet), 160), coalesce(p_rappel, false), nullif(trim(p_telephone), ''))
  returning * into d;
  insert into assistance_messages(demande_id, organisation_id, auteur, auteur_nom, de_plateforme, contenu, photo_path)
  values (d.id, d.organisation_id, p.id, p.full_name, false, left(trim(p_contenu), 4000), nullif(trim(p_photo), ''));
  return d;
end; $$;
revoke execute on function public.assistance_ouvrir(text, text, bigint, boolean, text, text) from anon;

-- Ajoute un message. Une réponse du client rouvre une demande résolue ;
-- une réponse de la plateforme fait passer la demande « en cours ».
create or replace function public.assistance_envoyer(p_demande bigint, p_contenu text, p_photo text default null)
returns public.assistance_messages language plpgsql security definer set search_path = public as $$
declare r text; d assistance_demandes; m assistance_messages; v_nom text;
begin
  r := public.assistance_role(p_demande);
  if r is null then raise exception 'Demande introuvable ou accès refusé.'; end if;
  if coalesce(trim(p_contenu), '') = '' then raise exception 'Le message est vide.'; end if;
  select * into d from assistance_demandes where id = p_demande;
  select full_name into v_nom from profiles where id = auth.uid();
  insert into assistance_messages(demande_id, organisation_id, auteur, auteur_nom, de_plateforme, contenu, photo_path)
  values (d.id, d.organisation_id, auth.uid(), case when r = 'plateforme' then 'Assistance PumpIT' else v_nom end,
          r = 'plateforme', left(trim(p_contenu), 4000), nullif(trim(p_photo), ''))
  returning * into m;
  update assistance_demandes set
    dernier_message_at = now(),
    non_lu_client = (r = 'plateforme') or non_lu_client,
    non_lu_plateforme = (r = 'client') or non_lu_plateforme,
    statut = case when r = 'client' and statut = 'resolue' then 'ouverte'
                  when r = 'plateforme' and statut = 'ouverte' then 'en_cours'
                  else statut end
  where id = d.id;
  return m;
end; $$;
revoke execute on function public.assistance_envoyer(bigint, text, text) from anon;

create or replace function public.assistance_marquer_lu(p_demande bigint)
returns void language plpgsql security definer set search_path = public as $$
declare r text;
begin
  r := public.assistance_role(p_demande);
  if r = 'plateforme' then update assistance_demandes set non_lu_plateforme = false where id = p_demande and non_lu_plateforme;
  elsif r = 'client' then update assistance_demandes set non_lu_client = false where id = p_demande and non_lu_client;
  end if;
end; $$;
revoke execute on function public.assistance_marquer_lu(bigint) from anon;

-- La plateforme fixe n'importe quel statut ; le client peut seulement clore sa demande.
create or replace function public.assistance_statut(p_demande bigint, p_statut text)
returns void language plpgsql security definer set search_path = public as $$
declare r text;
begin
  r := public.assistance_role(p_demande);
  if r is null then raise exception 'Demande introuvable ou accès refusé.'; end if;
  if p_statut not in ('ouverte', 'en_cours', 'resolue') then raise exception 'Statut inconnu.'; end if;
  if r = 'client' and p_statut <> 'resolue' then raise exception 'Vous pouvez seulement marquer la demande comme résolue.'; end if;
  update assistance_demandes set statut = p_statut where id = p_demande;
end; $$;
revoke execute on function public.assistance_statut(bigint, text) from anon;

-- ------------------------------------------------------------
-- 4. Photos jointes aux messages : droit de lecture
-- ------------------------------------------------------------
--  can_read_photo est régénérée pour inclure assistance_messages.photo_path :
--  la plateforme peut ainsi voir la photo jointe par un client.
do $$
declare c record; corps text;
begin
  corps := $q$exists (select 1 from public.stations s
                where s.id::text = split_part(p_name, '/', 1)
                  and (public.is_admin() or s.id = public.my_station() or public.has_station_access(s.id)))$q$;
  for c in
    select a.table_name, a.column_name from information_schema.columns a
    join pg_class k on k.relname = a.table_name and k.relnamespace = 'public'::regnamespace and k.relkind = 'r'
    where a.table_schema = 'public' and a.column_name like '%photo_path' and a.data_type = 'text'
    order by 1, 2
  loop
    corps := corps || format(E'\n    or exists (select 1 from public.%I t where t.%I = p_name)', c.table_name, c.column_name);
  end loop;
  execute 'create or replace function public.can_read_photo(p_name text) returns boolean '
       || 'language sql stable security invoker set search_path = public as $f$ select ' || corps || ' $f$';
end $$;

-- ------------------------------------------------------------
-- 5. Temps réel (les nouveaux messages arrivent sans recharger la page)
-- ------------------------------------------------------------
do $$
declare t text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach t in array array['assistance_demandes', 'assistance_messages'] loop
      if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t) then
        execute format('alter publication supabase_realtime add table public.%I', t);
      end if;
    end loop;
  end if;
end $$;

commit;
