-- ============================================================
--  v96 : MULTI-CLIENTS (une seule base pour plusieurs exploitants)
-- ============================================================
--  Principe
--    - Nouvelle table `organisations` (un client = une organisation).
--    - Chaque table métier reçoit une colonne `organisation_id`.
--    - Une règle RLS RESTRICTIVE par table (`tenant_isolation`) impose
--      organisation_id = organisation de l'utilisateur connecté.
--      Une règle restrictive s'AJOUTE aux règles existantes (ET logique) :
--      les ~90 règles actuelles restent inchangées et continuent de
--      s'appliquer, mais à l'intérieur d'une seule organisation.
--    - Les vues sont toutes en security_invoker : elles héritent donc
--      du cloisonnement sans être réécrites.
--
--  Données existantes : tout est rattaché à l'organisation n° 1.
--
--  Choix assumés
--    - `settings` : une ligne par organisation. Chaque ligne garde id = 1
--      (la clé devient organisation_id). Les vues et l'application lisent
--      `settings where id = 1` : avec le cloisonnement, elles tombent sur
--      la ligne de l'organisation courante, sans réécriture.
--    - Rôles et permissions : communs à toutes les organisations.
--      Seul l'administrateur de la plateforme peut les modifier.
--    - L'administrateur de la plateforme (profiles.is_platform_admin)
--      travaille toujours dans UNE organisation à la fois et en change
--      avec switch_organisation(). Il n'y a jamais de vue mélangée.
--
--  À exécuter dans Supabase > SQL Editor, APRÈS une sauvegarde, et
--  d'abord sur une copie de la base. Le script est transactionnel :
--  en cas d'erreur, rien n'est modifié. Il peut être relancé.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1. Organisations
-- ------------------------------------------------------------
create table if not exists public.organisations (
  id bigint generated by default as identity primary key,
  nom text not null,
  code_invitation text not null unique default upper(substr(md5(gen_random_uuid()::text), 1, 8)),
  created_at timestamptz not null default now()
);

insert into public.organisations (id, nom) values (1, 'Client initial')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.organisations', 'id'), greatest((select max(id) from public.organisations), 1));

alter table public.profiles add column if not exists organisation_id bigint references public.organisations(id);
alter table public.profiles add column if not exists is_platform_admin boolean not null default false;
create index if not exists idx_profiles_organisation on public.profiles(organisation_id);

-- Les triggers utilisateur sont coupés le temps du rattachement (sinon
-- prevent_role_change & co. s'exécutent pour rien sur chaque ligne).
alter table public.profiles disable trigger user;
update public.profiles set organisation_id = 1 where organisation_id is null;
alter table public.profiles enable trigger user;

-- ------------------------------------------------------------
-- 2. Fonctions d'identité
-- ------------------------------------------------------------
create or replace function public.current_org_id()
returns bigint language sql stable security definer set search_path = public as $$
  select organisation_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_platform_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select is_platform_admin from public.profiles where id = auth.uid()), false);
$$;

-- Renseigne organisation_id à l'insertion.
--   1) si la ligne porte une station, l'organisation est celle de la station
--      (couvre aussi les insertions sans utilisateur : pg_cron, fonction OCR) ;
--   2) sinon, celle de l'utilisateur connecté.
-- La règle tenant_isolation vérifie ensuite que le résultat est bien
-- l'organisation de l'utilisateur : impossible d'écrire chez un autre client.
create or replace function public.set_organisation_id()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_station bigint; v_org bigint;
begin
  v_station := nullif(to_jsonb(new) ->> 'station_id', '')::bigint;
  if v_station is not null then
    select organisation_id into v_org from public.stations where id = v_station;
  end if;
  if v_org is null then
    v_org := coalesce(new.organisation_id, public.current_org_id());
  end if;
  new.organisation_id := v_org;
  return new;
end; $$;
revoke execute on function public.set_organisation_id() from anon, authenticated;

-- ------------------------------------------------------------
-- 3. Colonne organisation_id + cloisonnement sur toutes les tables métier
-- ------------------------------------------------------------
--  Boucle dynamique : s'appuie sur le schéma réel de la base, pas sur une
--  liste figée. Tables exclues :
--    organisations, profiles      -> traitées à part (sections 4 et 5)
--    roles, permissions, role_permissions -> communes à tous (section 6)
do $$
declare
  t record;
  exclues text[] := array['organisations','profiles','roles','permissions','role_permissions'];
  nullable text[] := array['audit_log'];   -- lignes écrites par trigger, parfois sans station ni utilisateur
begin
  -- `stations` en premier : le trigger des autres tables lit stations.organisation_id.
  for t in
    select c.relname as nom, c.relrowsecurity as rls
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relname <> all(exclues)
    order by (c.relname <> 'stations'), c.relname
  loop
    execute format('alter table public.%I add column if not exists organisation_id bigint references public.organisations(id)', t.nom);

    -- Rattachement de l'existant à l'organisation 1, triggers d'audit coupés
    -- (sinon chaque ligne mise à jour créerait une entrée dans audit_log).
    execute format('alter table public.%I disable trigger user', t.nom);
    execute format('update public.%I set organisation_id = 1 where organisation_id is null', t.nom);
    execute format('alter table public.%I enable trigger user', t.nom);

    execute format('alter table public.%I alter column organisation_id set default public.current_org_id()', t.nom);
    if t.nom <> all(nullable) then
      execute format('alter table public.%I alter column organisation_id set not null', t.nom);
    end if;
    execute format('create index if not exists %I on public.%I(organisation_id)', 'idx_' || t.nom || '_org', t.nom);

    execute format('drop trigger if exists trg_set_organisation on public.%I', t.nom);
    execute format('create trigger trg_set_organisation before insert on public.%I for each row execute function public.set_organisation_id()', t.nom);

    execute format('drop policy if exists tenant_isolation on public.%I', t.nom);
    execute format($p$create policy tenant_isolation on public.%I as restrictive for all
      using (organisation_id = (select public.current_org_id()))
      with check (organisation_id = (select public.current_org_id()))$p$, t.nom);

    if not t.rls then
      raise warning 'Table % : RLS désactivé. La règle tenant_isolation est créée mais INACTIVE tant que le RLS n''est pas activé sur cette table.', t.nom;
    end if;
  end loop;
end $$;

-- ------------------------------------------------------------
-- 4. Profils
-- ------------------------------------------------------------
--  Chacun voit toujours son propre profil. Au-delà : uniquement les profils
--  de son organisation. Les comptes sans organisation (code d'invitation
--  absent ou erroné à l'inscription) ne sont visibles que de l'administrateur
--  de la plateforme, qui les rattache.
drop policy if exists tenant_isolation on public.profiles;
create policy tenant_isolation on public.profiles as restrictive for all
  using (
    id = auth.uid()
    or organisation_id = (select public.current_org_id())
    or (organisation_id is null and (select public.is_platform_admin()))
  )
  with check (
    id = auth.uid()
    or organisation_id = (select public.current_org_id())
    or (select public.is_platform_admin())
  );

-- Personne ne change d'organisation ni ne se nomme administrateur de la
-- plateforme depuis l'application. Même logique que prevent_role_change :
-- le garde-fou ne vise que le rôle `authenticated` (l'éditeur SQL et les
-- fonctions security definer ci-dessous ne sont pas concernés).
create or replace function public.prevent_org_change()
returns trigger language plpgsql set search_path = public as $$
begin
  if current_user = 'authenticated' then
    if new.is_platform_admin is distinct from old.is_platform_admin then
      raise exception 'Le statut d''administrateur de la plateforme ne se modifie pas depuis l''application.';
    end if;
    if new.organisation_id is distinct from old.organisation_id and not public.is_platform_admin() then
      raise exception 'Seul l''administrateur de la plateforme peut changer l''organisation d''un compte.';
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists trg_prevent_org_change on public.profiles;
create trigger trg_prevent_org_change before update on public.profiles
  for each row execute function public.prevent_org_change();

-- Inscription : le code d'invitation saisi à la création du compte rattache
-- le nouveau profil à son organisation. Le compte reste « en attente » :
-- l'administrateur du client le valide et lui attribue une station, comme avant.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_org bigint;
begin
  select id into v_org from public.organisations
  where code_invitation = upper(trim(coalesce(new.raw_user_meta_data ->> 'org_code', '')));
  insert into public.profiles(id, full_name, role, approved, organisation_id)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email), 'gerant', false, v_org)
  on conflict (id) do nothing;
  return new;
end; $$;
revoke execute on function public.handle_new_user() from anon, authenticated;

-- ------------------------------------------------------------
-- 5. Table organisations : accès
-- ------------------------------------------------------------
alter table public.organisations enable row level security;
grant select, insert, update, delete on public.organisations to authenticated;

drop policy if exists p_org_sel on public.organisations;
create policy p_org_sel on public.organisations for select to authenticated
  using (id = (select public.current_org_id()) or (select public.is_platform_admin()));

drop policy if exists p_org_write on public.organisations;
create policy p_org_write on public.organisations for all to authenticated
  using ((select public.is_platform_admin())) with check ((select public.is_platform_admin()));

-- ------------------------------------------------------------
-- 6. Rôles et permissions : communs, modifiables par la plateforme seule
-- ------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['roles','role_permissions','permissions'] loop
    if to_regclass('public.' || t) is null then continue; end if;
    execute format('drop policy if exists platform_only_ins on public.%I', t);
    execute format('drop policy if exists platform_only_upd on public.%I', t);
    execute format('drop policy if exists platform_only_del on public.%I', t);
    execute format('create policy platform_only_ins on public.%I as restrictive for insert with check ((select public.is_platform_admin()))', t);
    execute format('create policy platform_only_upd on public.%I as restrictive for update using ((select public.is_platform_admin())) with check ((select public.is_platform_admin()))', t);
    execute format('create policy platform_only_del on public.%I as restrictive for delete using ((select public.is_platform_admin()))', t);
  end loop;
end $$;

-- ------------------------------------------------------------
-- 7. Réglages : une ligne par organisation
-- ------------------------------------------------------------
--  La clé primaire passe de (id) à (organisation_id). Chaque ligne garde
--  id = 1 (la contrainte CHECK id = 1 reste en place).
do $$
declare pk record;
begin
  select con.conname,
         (select array_agg(a.attname::text) from unnest(con.conkey) k join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k) as cols
    into pk
  from pg_constraint con where con.conrelid = 'public.settings'::regclass and con.contype = 'p';
  if pk.conname is not null and pk.cols <> array['organisation_id'] then
    execute format('alter table public.settings drop constraint %I', pk.conname);
    alter table public.settings add constraint settings_pkey primary key (organisation_id);
  end if;
end $$;

-- ------------------------------------------------------------
-- 8. Unicités « par nom » : désormais par organisation
-- ------------------------------------------------------------
--  Sans cela, deux clients ne pourraient pas avoir un produit du même nom.
--  Les unicités qui contiennent déjà station_id sont cloisonnées de fait.
do $$
declare
  cible record; con record;
begin
  for cible in
    select * from (values
      ('products',         array['categorie','nom']),
      ('lubrifiant_types', array['nom']),
      ('suppliers',        array['nom']),
      ('suppliers',        array['categorie','nom']),
      ('stations',         array['nom'])
    ) as v(tbl, cols)
  loop
    if to_regclass('public.' || cible.tbl) is null then continue; end if;
    for con in
      select c.conname from pg_constraint c
      where c.conrelid = ('public.' || cible.tbl)::regclass and c.contype = 'u'
        and (select array_agg(a.attname::text order by a.attname::text)
             from unnest(c.conkey) k join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k)
            = (select array_agg(x order by x) from unnest(cible.cols) x)
    loop
      execute format('alter table public.%I drop constraint %I', cible.tbl, con.conname);
      execute format('alter table public.%I add constraint %I unique (organisation_id, %s)',
        cible.tbl, cible.tbl || '_org_' || array_to_string(cible.cols, '_') || '_key',
        (select string_agg(quote_ident(x), ', ') from unnest(cible.cols) x));
    end loop;
  end loop;
end $$;

-- ------------------------------------------------------------
-- 9. Fonctions security definer : elles contournent le RLS, donc on les borne
-- ------------------------------------------------------------
create or replace function public.jours_correction_gerant()
returns integer language sql stable security definer set search_path = public as $$
  select coalesce((select jours_correction_gerant from settings where organisation_id = public.current_org_id()), 2);
$$;

create or replace function public.purge_attachments_archivables() returns integer
language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if not is_admin() then raise exception 'admin uniquement'; end if;
  delete from attachments a using v_attachments_archivables v
  where a.id = v.id and a.organisation_id = public.current_org_id();
  get diagnostics n = row_count;
  return n;
end $$;
revoke execute on function public.purge_attachments_archivables() from anon;

create or replace function public.apply_price_request()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.statut = 'validee' and old.statut is distinct from 'validee' then
    update products set prix_achat = new.prix_demande
    where id = new.product_id and organisation_id = new.organisation_id;
  end if;
  return new;
end; $$;

-- ------------------------------------------------------------
-- 10. Gestion des clients (administrateur de la plateforme)
-- ------------------------------------------------------------
-- Crée un client. Ses réglages (prix, marges, seuils) sont copiés depuis
-- l'organisation courante : son administrateur les ajuste ensuite.
create or replace function public.create_organisation(p_nom text)
returns public.organisations language plpgsql security definer set search_path = public as $$
declare v_org public.organisations;
begin
  if not public.is_platform_admin() then raise exception 'Réservé à l''administrateur de la plateforme.'; end if;
  if coalesce(trim(p_nom), '') = '' then raise exception 'Le nom du client est obligatoire.'; end if;
  insert into organisations(nom) values (trim(p_nom)) returning * into v_org;
  insert into settings
  select (jsonb_populate_record(null::settings, to_jsonb(s) || jsonb_build_object('organisation_id', v_org.id))).*
  from settings s where s.organisation_id = public.current_org_id();
  if not found then
    insert into settings(id, organisation_id) values (1, v_org.id);
  end if;
  return v_org;
end; $$;
revoke execute on function public.create_organisation(text) from anon;

-- Fait passer l'administrateur de la plateforme dans une autre organisation.
create or replace function public.switch_organisation(p_org bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_platform_admin() then raise exception 'Réservé à l''administrateur de la plateforme.'; end if;
  if not exists (select 1 from organisations where id = p_org) then raise exception 'Organisation inconnue.'; end if;
  update profiles set organisation_id = p_org, station_id = null where id = auth.uid();
  delete from profile_stations where profile_id = auth.uid();
end; $$;
revoke execute on function public.switch_organisation(bigint) from anon;

-- Rattache un compte inscrit sans code valide (ou déplace un compte) vers une organisation.
create or replace function public.assign_organisation(p_profile uuid, p_org bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_platform_admin() then raise exception 'Réservé à l''administrateur de la plateforme.'; end if;
  if not exists (select 1 from organisations where id = p_org) then raise exception 'Organisation inconnue.'; end if;
  update profiles set organisation_id = p_org, station_id = null where id = p_profile;
  delete from profile_stations where profile_id = p_profile;
end; $$;
revoke execute on function public.assign_organisation(uuid, bigint) from anon;

-- ------------------------------------------------------------
-- 11. Photos : un administrateur ne liste que les dossiers de ses stations
-- ------------------------------------------------------------
--  Les chemins commencent par `${stationId}/…`. La sous-requête sur
--  `stations` est elle-même cloisonnée : elle ne trouve que les stations
--  de l'organisation de l'utilisateur.
--  Rappel : le bucket reste public par URL directe (voir README).
do $$
begin
  if to_regclass('storage.objects') is not null
     and exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'bordereaux_read') then
    drop policy if exists "bordereaux_read" on storage.objects;
    create policy "bordereaux_read" on storage.objects for select to authenticated
      using (bucket_id = 'bordereaux'
        and exists (select 1 from public.stations s where s.id::text = (storage.foldername(name))[1])
        and (is_admin() or (storage.foldername(name))[1] = my_station()::text));
    drop policy if exists "bordereaux_insert" on storage.objects;
    create policy "bordereaux_insert" on storage.objects for insert to authenticated
      with check (bucket_id = 'bordereaux'
        and exists (select 1 from public.stations s where s.id::text = (storage.foldername(name))[1])
        and (is_admin() or (storage.foldername(name))[1] = my_station()::text));
  end if;
end $$;

-- ------------------------------------------------------------
-- 12. Vues : réglages de l'organisation courante, security_invoker partout
-- ------------------------------------------------------------
--  Plusieurs vues lisent `settings where id = 1`. Pour un utilisateur de
--  l'application, le cloisonnement suffit (une seule ligne visible). Mais
--  sans RLS (éditeur SQL, service_role), il y aurait une ligne par client
--  et la sous-requête échouerait (« more than one row »). On remplace donc
--  ce filtre par l'organisation courante dans la définition de ces vues.
--  Colonnes inchangées : les vues dépendantes ne sont pas touchées.
do $$
declare v record; def text;
begin
  for v in select c.oid, c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = 'public' and c.relkind = 'v'
  loop
    def := pg_get_viewdef(v.oid);
    if position('settings.id = 1' in def) > 0 then
      def := replace(def, 'settings.id = 1', 'settings.organisation_id = public.current_org_id()');
      execute format('create or replace view public.%I as %s', v.relname, def);
    elsif def ~ '\msettings\M' and position('current_org_id()' in def) = 0 then
      raise warning 'Vue % : lit settings sous une forme non reconnue, à relire à la main.', v.relname;
    end if;
  end loop;
end $$;

-- create or replace view réinitialise les options : on (ré)applique
-- security_invoker à toutes les vues, sinon elles contournent le RLS.
do $$
declare v text;
begin
  for v in select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = 'public' and c.relkind = 'v'
  loop
    execute format('alter view public.%I set (security_invoker = on)', v);
  end loop;
end $$;

-- ------------------------------------------------------------
-- 13. Contrôles : le script échoue si le cloisonnement est incomplet
-- ------------------------------------------------------------
do $$
declare manquantes text;
begin
  select string_agg(c.relname, ', ') into manquantes
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
    and c.relname not in ('organisations','roles','permissions','role_permissions')
    and not exists (select 1 from pg_policies p where p.schemaname = 'public' and p.tablename = c.relname and p.policyname = 'tenant_isolation');
  if manquantes is not null then
    raise exception 'Tables sans règle tenant_isolation : %', manquantes;
  end if;
end $$;

commit;

-- ============================================================
--  APRÈS LE SCRIPT (à faire une fois, à la main)
-- ============================================================
--  1) Vous nommer administrateur de la plateforme (remplacez l'e-mail) :
--
--     update public.profiles set is_platform_admin = true
--     where id = (select id from auth.users where email = 'vous@exemple.com');
--
--  2) Renommer le client initial :
--
--     update public.organisations set nom = 'Nom de votre société' where id = 1;
--
--  3) Relire les fonctions security definer qui ne viennent pas de ce dépôt
--     (elles contournent le RLS) :
--
--     select proname from pg_proc
--     where pronamespace = 'public'::regnamespace and prosecdef order by 1;
--
--  4) Relire les unicités qui ne contiennent ni station_id ni organisation_id :
--
--     select conrelid::regclass, pg_get_constraintdef(oid) from pg_constraint
--     where connamespace = 'public'::regnamespace and contype = 'u'
--       and pg_get_constraintdef(oid) !~ '(station_id|organisation_id)';
