-- ============================================================
--  SEED — Inventaire supérette WEZON Y TRYFA au 01/06/2026
--  (station Beaurivage), importé depuis le PDF fourni par l'utilisateur.
--
--  212 articles répartis en 8 blocs dans le PDF (déco fête, épicerie
--  sucrée, boissons, cuisine/droguerie, hygiène, parfumerie, laitier/
--  pâtisserie, divers) — IGNORÉS ici à la demande de l'utilisateur :
--  `products.categorie` reste 'superette' pour tous, sans sous-
--  catégorie. L'ordre d'origine du PDF est préservé via `ordre`
--  (N° d'ordre × 10) pour garder le regroupement visuel implicite
--  dans Products.jsx.
--
--  PRIX : le PDF ne donne qu'un "PRIX UNITAIRE" (prix de vente,
--  utilisé pour valoriser le stock) — traité ici comme `prix_vente`.
--  `prix_achat` (coût) est INCONNU et reste donc NULL (pas dans la
--  liste de colonnes insérées, donc jamais écrasé par l'upsert).
--
--  STOCK : chaque "STOCK FINAL" du PDF devient un mouvement
--  `stock_movements` unique (type='ajustement', source='inventaire',
--  date_mouvement='2026-06-01'), conformément à v118 (stock supérette
--  = somme des mouvements, sans déclaration quotidienne). Tagués avec
--  ref='inventaire-wezon-2026-06-01' et précédés d'un DELETE sur ce
--  ref : le script est donc rejouable sans dupliquer les mouvements.
--
--  CAS PARTICULIER — ligne 39 "NIDO-LAIT EN POUDRE" : le PDF la
--  marque "EXPIRE — A RETRANCHER" (péremption 31/03/2026, déjà
--  dépassée au 01/06/2026). Le schéma n'a pas de champ péremption ;
--  on applique donc littéralement l'instruction du PDF en import ant
--  un mouvement à quantité 0 (au lieu de 2) et en gardant le détail
--  en note. Le produit est quand même créé (actif) au cas où du stock
--  frais serait réceptionné plus tard.
--
--  Deux lignes à stock 0 dans le PDF (n°22 assiettes plastique,
--  n°46 vin mousseux Sirebeaupré) : produit créé, mouvement à 0.
--
--  À exécuter dans Supabase > SQL Editor > Run. Idempotente.
-- ============================================================

insert into products (categorie, nom, unite, prix_vente, actif, ordre) values
('superette','BALLON MULTI-COLORE-CRF SACHETS 20 PCS','unité',2500,true,10),
('superette','BALLON MULTI-COLORE-SACHETS 10 PCS','unité',2300,true,20),
('superette','BALLON METAL 30 M MULTI-CRF-ACHAT 12 PCS','unité',2300,true,30),
('superette','BOUGIE HAPPY BIRTHDAY CRF','unité',1500,true,40),
('superette','20 BOUGIES+20 BOBECHES BLEU-CRF','unité',1000,true,50),
('superette','20 BOUGIES+20 BOBECHES BLANC-CRF','unité',1000,true,60),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 0','unité',850,true,70),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 1','unité',850,true,80),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 2','unité',850,true,90),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 3','unité',850,true,100),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 4','unité',850,true,110),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 5','unité',850,true,120),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 6','unité',850,true,130),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 7','unité',850,true,140),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 8','unité',850,true,150),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 9','unité',850,true,160),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 0','unité',1000,true,170),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 3','unité',1000,true,180),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 4','unité',1000,true,190),
('superette','BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 9','unité',1000,true,200),
('superette','ASSIETTES BLANCHES CARTON 23 CM CRF-SACHET 50 PCS','unité',3000,true,210),
('superette','ASSIETTES PLASTIQUE GRAND FORMAT SACHET 50 PCS','unité',1850,true,220),
('superette','SERVIETTE BLANCHE SACHET DE 100','unité',1000,true,230),
('superette','ASSIETTES EN CARTON PIRATE CARTE AUX TRESORS-SACHET 6 PCS','unité',1600,true,240),
('superette','ASSIETTES EN PAPIER PIRATE CARTE AUX TRESORS-SACHET 20 PCS','unité',1600,true,250),
('superette','ASSIETTE 23 CM EN CARTON LICORNE-SACHET 6PCS','unité',1650,true,260),
('superette','ASSIETTES EN PAPIER LICORNE-SACHET 20 PCS','unité',1600,true,270),
('superette','ARACHIDE BOUTEILLE','unité',2000,true,280),
('superette','AMUSE BOUCHE BOUTEILLE','unité',1400,true,290),
('superette','CACAHUETE','unité',1300,true,300),
('superette','ACADJOU BOUTEILLE','unité',5000,true,310),
('superette','COCO RAPE','unité',1700,true,320),
('superette','AKLUI','unité',1200,true,330),
('superette','MIEL 1 LITRE','unité',3100,true,340),
('superette','MIEL 0,5 LITRE','unité',1700,true,350),
('superette','MIEL 0,3 LITRE','unité',850,true,360),
('superette','BISCUIT AUX RAISINS (MADELEINE)','unité',1000,true,370),
('superette','CHIPS BANANE','unité',200,true,380),
('superette','NIDO-LAIT EN POUDRE','unité',4300,true,390),
('superette','SUCRE ROUX DADDY','unité',4100,true,400),
('superette','FILTRE A CAFE BRUN N°4-CRF-BTEC-80','unité',1200,true,410),
('superette','CAFE SOLUBLE-BOUTEILLE','unité',3400,true,420),
('superette','VIN ROUGE-COTES DU RHÔNE','unité',6500,true,430),
('superette','VIN MOUSSEUX-COMTE DE TALMON-DEMI-SEC','unité',3200,true,440),
('superette','VIN MOUSSEUX-COMTE DE TALMON-BRUT','unité',3200,true,450),
('superette','VIN MOUSSEUX-DEMI SEC BLANC-SIREBEAUPRE','unité',3000,true,460),
('superette','VIN MOUSSEUX-JP,CHENET','unité',6500,true,470),
('superette','VIN ROUGE-CHÂTEAU LA ROSE DE HAUT MOUSCHET','unité',11000,true,480),
('superette','VIN ROUGE-CHÂTEAU TRAPAUD','unité',13700,true,490),
('superette','VIN ROUGE-HAUT MEDEC','unité',7500,true,500),
('superette','VIN ROUGE-SYRAH-GRANDE RESERVE-MAISON CASTEL','unité',6700,true,510),
('superette','VIN ROUGE-BARON ROMEO','unité',2100,true,520),
('superette','VIN ROUGE-PORTO ROCHEZ','unité',7000,true,530),
('superette','VIN BLANC-PORTO ROCHEZ','unité',7000,true,540),
('superette','VIN BLANC-ENTRE DEUX MERS','unité',4200,true,550),
('superette','VIN BLANC-GEWURZTRAMINER','unité',5000,true,560),
('superette','VIN BLANC-HAUTVALLON','unité',3500,true,570),
('superette','VIN BLANC-BARON DE LESTAC','unité',5600,true,580),
('superette','VIN BLANC-VUE 11°-FIN BOUQUET BTLVNC 75CL','unité',2000,true,590),
('superette','VIN BLANC-COMTE DE SIRAC','unité',2800,true,600),
('superette','VIN BLANC-LAVILLE PAVILLON','unité',6000,true,610),
('superette','VIN ROSE-FRAMBOISE-OH MY FRAMB','unité',2500,true,620),
('superette','VIN ROSE-PAMPLEMOUSSE-OH MY PAMP','unité',2500,true,630),
('superette','VIN ROSE-SYRAH GRENACHE','unité',3800,true,640),
('superette','VIN ROSE-CABERNET D''ANJOU','unité',6700,true,650),
('superette','VIN ROSE-BORDERIVE','unité',3500,true,660),
('superette','SPIRITUEUX VSOP BRANDY-OLIVIER DE BAUPREAU BTL VNC-70 CL','unité',3800,true,670),
('superette','SPIRITUEUX 40% ARMAGNAC','unité',6000,true,680),
('superette','VIN DE BORDEAUX MOELLEUX','unité',4000,true,690),
('superette','VIN DE BORDEAUX-APPELLATION','unité',2950,true,700),
('superette','VIN DE BORDEAUX-PAVILLON LA TOURELLE','unité',10500,true,710),
('superette','VIN MALESAN-BORDEAUX','unité',7700,true,720),
('superette','PASTIS-BELLE France','unité',2500,true,730),
('superette','WILLIAM LAWSON''S-WHISKY','unité',7200,true,740),
('superette','WILLIAM PEEL-WHISKY','unité',4000,true,750),
('superette','LABEL 5-WHISKY','unité',5800,true,760),
('superette','BLACK LABEL 70 CL-WHISKY','unité',1600,true,770),
('superette','GIN BARMON''S','unité',2800,true,780),
('superette','SPIRIT 24% LORD WYLL-WHISKY','unité',1500,true,790),
('superette','BLENDED 40% WESTERLY-WHISKY','unité',2000,true,800),
('superette','CAMPARI','unité',12000,true,810),
('superette','MARTINI-BLANC','unité',6900,true,820),
('superette','MARTINI-ROUGE','unité',6900,true,830),
('superette','CREME DE CASSIS','unité',4500,true,840),
('superette','EAU MINERALE-AQUABELLE-1,5 LITRE','unité',500,true,850),
('superette','EAU MINERALE-AQUABELLE-PACK DE 06','unité',2000,true,860),
('superette','EAU MINERALE WEZON-EN VERRE JETTABLE','unité',100,true,870),
('superette','EAU MINERALE WEZON-EN VERRE JETTABLE-PACK DE 05','unité',450,true,880),
('superette','POSSOTOME GAZEIFIEE-1,5 LITRE','unité',600,true,890),
('superette','POSSOTOME GAZEIFIEE-PACK DE 06','unité',2300,true,900),
('superette','POSSO CITRON-1 LITRE','unité',600,true,910),
('superette','POSSO CITRON-PACK DE 06','unité',2300,true,920),
('superette','YOUKI COCKTAIL DE FRUIT 50 CL','unité',400,true,930),
('superette','YOUKI COCKTAIL DE FRUIT 50 CL-PACK DE 06','unité',2000,true,940),
('superette','YOUKI PAMPLEMOUSSE-50 CL','unité',400,true,950),
('superette','YOUKI PAMPLEMOUSSE-50 CL-PACK DE 06','unité',2000,true,960),
('superette','WORLD COLA','unité',400,true,970),
('superette','WORLD COLA-PACK DE 07','unité',2000,true,980),
('superette','XXL 30 CL','unité',500,true,990),
('superette','NECTAR DE BAOBAB-AU LAIT DE COCO-GOLDEN ICE','unité',600,true,1000),
('superette','NECTAR DE BAOBAB-AU LAIT DE COCO-GOLDEN ICE-PACK DE 06','unité',3000,true,1010),
('superette','NECTAR DE BAOBAB-GOLDEN ICE','unité',500,true,1020),
('superette','NECTAR DE BAOBAB-GOLDEN ICE-PACK DE 06','unité',2500,true,1030),
('superette','PUR JUS D''ANANAS-GOLDEN ICE','unité',500,true,1040),
('superette','PUR JUS D''ANANAS-GOLDEN ICE-PACK DE 06','unité',2500,true,1050),
('superette','JUS DE FRUIT-GOLDEN ICE-ANANAS,ORANGE,GINGEMBRE','unité',500,true,1060),
('superette','JUS DE FRUIT-GOLDEN ICE-ANANAS,ORANGE,GINGEMBRE-PACK DE 06','unité',2500,true,1070),
('superette','JUS DE FRUIT-GOLDEN ICE-ANANAS,PASQUETTE','unité',500,true,1080),
('superette','JUS DE FRUIT-GOLDEN ICE-ANANAS,PASQUETTE-PACK DE 06','unité',2500,true,1090),
('superette','JUS GOLDEN DETOX-GOLDEN ICE','unité',500,true,1100),
('superette','JUS GOLDEN DETOX-GOLDEN ICE-PACK DE 06','unité',2700,true,1110),
('superette','BIERE BLONDE FORTE','unité',900,true,1120),
('superette','RIZ PARFUME-DIVINE-5KG','unité',6600,true,1130),
('superette','RIZ PARFUME-DIVINE-5KG-PACK DE 05','unité',30000,true,1140),
('superette','RIZ PARFUME-DIVINE-1KG','unité',1600,true,1150),
('superette','MATANTI-PATE ALIMENTAIRE','unité',300,true,1160),
('superette','SEL DE TABLE FIN','unité',900,true,1170),
('superette','BICARBONATE DE SODIUM','unité',550,true,1180),
('superette','FILM 2 EN 1-BELLE France','unité',900,true,1190),
('superette','PAPIER CUISSON','unité',1550,true,1200),
('superette','SACHETS DE GLAÇONS','unité',900,true,1210),
('superette','SACHETS-SACS DE CONGELATION-ZIP','unité',2400,true,1220),
('superette','VINAIGRE D''ALCOOL BLANC CHRISTAL','unité',900,true,1230),
('superette','EPONGE BOULES-BOLLEN INOX','unité',700,true,1240),
('superette','EPONGE CARRE-VAISSELLE-CFR','unité',1100,true,1250),
('superette','EPONGE CARRE-VAISSELLE-BELLE France','unité',1050,true,1260),
('superette','TAMPON SUREPONGE-BELLE France','unité',950,true,1270),
('superette','SACS POUBELLES-PRIX MINI-30 LITRES','unité',850,true,1280),
('superette','SACS POUBELLES-LIEN COULISSANT-CFR-100 LITRES','unité',1900,true,1290),
('superette','SACS POUBELLES-SPECIAL CONTAINER-CFR-120 LITRES','unité',1300,true,1300),
('superette','PAPIER TOILETTE DOUCHE-BELLE France','unité',1800,true,1310),
('superette','PATE DENTIFRICE-SIGNAL-EXTRA FRAICHEUR-75 ML','unité',1400,true,1320),
('superette','PATE DENTIFRICE-SIGNAL-INTERGAL COCO-75 ML','unité',1400,true,1330),
('superette','PATE DENTIFRICE-SIGNAL-SEL ROSE & CAMOMILLE-75 ML','unité',1500,true,1340),
('superette','PATE DENTIFRICE-SIGNAL-CRYSTAL GEL-75 ML','unité',1750,true,1350),
('superette','PATE DENTIFRICE-SIGNAL-INTERGAL BICARBONATE-75 ML','unité',1450,true,1360),
('superette','PATE DENTIFRICE-HALEINE PUR-75 ML','unité',1400,true,1370),
('superette','PATE DENTIFRICE-SIGNAL-INTERGAL CHARBON-75 ML','unité',1400,true,1380),
('superette','PATE DENTIFRICE-SIGNAL-INTERGAL INTERDENTAIRE-75 ML','unité',1500,true,1390),
('superette','PATE DENTIFRICE-SIGNAL-0-3 ANS-50 ML','unité',1550,true,1400),
('superette','PATE DENTIFRICE-SIGNAL-3-6 ANS-50 ML','unité',1650,true,1410),
('superette','BROSSE A DENT SIGNAL','unité',3000,true,1420),
('superette','RASOIRS-SIMPLE CHOICE JETABLE','unité',2500,true,1430),
('superette','MOUSSE A RASER-HOMME-PRIX MINI','unité',1500,true,1440),
('superette','TAMPON AVEC APPLICATEUR','unité',2000,true,1450),
('superette','SERVIETTE ULTRA','unité',1300,true,1460),
('superette','NANA SERVIETTE-HYGIENE','unité',2400,true,1470),
('superette','SAVON FANICO PETIT','unité',300,true,1480),
('superette','SAVON FANICO MOYEN','unité',400,true,1490),
('superette','BLOCS WC-LAVANDE','unité',1500,true,1500),
('superette','BLOCS WC-EXPERT FRESH OCEAN-3 IN 1','unité',1100,true,1510),
('superette','PASTILLES JAVEL','unité',2000,true,1520),
('superette','CREME A RECURER-EXPERT POWER CREAM-CITRON-750 ML','unité',1400,true,1530),
('superette','CREME A RECURER AVEC JAVEL-EXPERT POWER CREAM-ANANAS-750 ML','unité',1850,true,1540),
('superette','POUDRE A RECURER-AJAX JAVEL-750 G','unité',1800,true,1550),
('superette','EXPRESS-EXPERT DEBOUCHEUR GEL-CFR-13 TL-1 LITRE','unité',2200,true,1560),
('superette','NETTOYANT MENAGER-FRAICHEUR VERTE-VIGOR','unité',2150,true,1570),
('superette','DEODORANT NARTA-HOMME-INVIS MAX','unité',4350,true,1580),
('superette','DEODORANT NARTA-HOMME-PROTECTION 5','unité',3650,true,1590),
('superette','DEODORANT NARTA-COLOGNE','unité',3650,true,1600),
('superette','DEODORANT USHUAÏA','unité',3650,true,1610),
('superette','DEODORANT EBENE-EVASION TROPICAL','unité',1900,true,1620),
('superette','DEODORANT DOVE-INVISIBLE DRY','unité',3550,true,1630),
('superette','DEODORANT DOVE-ORIGINAL','unité',3550,true,1640),
('superette','DEODORANT DOVE-ADVANCED CARE','unité',3550,true,1650),
('superette','DEODORANT DOVE-ROLL ON STICK','unité',3700,true,1660),
('superette','DEODORANT L''OREAL-MEN EXPERT','unité',4000,true,1670),
('superette','DEODORANT BYPHASSE','unité',2250,true,1680),
('superette','RED FRUIT GOUGIE','unité',2000,true,1690),
('superette','GEL SHAMPOOING DOUCHE-CEDRE','unité',1100,true,1700),
('superette','GEL SHAMPOOING DOUCHE-AGRUMES','unité',1100,true,1710),
('superette','GEL DOUCHE-FRESH-3 IN 1','unité',1500,true,1720),
('superette','GEL SHAMPOOING-BAIN DOUCHE ENFANTS-KIDS','unité',1300,true,1730),
('superette','CREME DE DOUCHE-WITH VANILLE','unité',1500,true,1740),
('superette','CREME DE DOUCHE-WITH COCO','unité',1500,true,1750),
('superette','REPAIRING-LAIT CORPOREL REPARATEUR-CFR','unité',1500,true,1760),
('superette','LAIT DEMAQUILLANT-BELLE France-200 ML','unité',1100,true,1770),
('superette','LAIT CORP HYDRATANT-SIMPLE CHOICE','unité',3200,true,1780),
('superette','MIXA-LAIT DE BEAUTE-ANTI DESSECHEMENT-NUTRITION','unité',4850,true,1790),
('superette','MIXA-LAIT DE BEAUTE-ANTI DESSECHEMENT-BEAUTE','unité',4850,true,1800),
('superette','MIXA BEBE LAIT DE TOILETTE','unité',3350,true,1810),
('superette','COTON-DISQUES A DEMAQUILLER-PRIX MINI','unité',950,true,1820),
('superette','COTON SACHET-200 G','unité',2000,true,1830),
('superette','PANSEMENTS UNIVERSELS','unité',1200,true,1840),
('superette','LIQUIDE VAISSELLE-PEAUX SENSIBLES-500 ML','unité',1200,true,1850),
('superette','ULTRA DEGRAISSANT-PEAUX SENSIBLES-BELLE France-500 ML','unité',1200,true,1860),
('superette','LIQUIDE DE VAISSELLE-DEGRAISSANT-CITRON-BELLE France-750 ML','unité',1350,true,1870),
('superette','LIQUIDE DE VAISSELLE-PRIX MINI-FRUITS ROUGE-500 ML','unité',875,true,1880),
('superette','LIQUIDE DE VAISSELLE-PRIX MINI-CITRON-500 ML','unité',875,true,1890),
('superette','NETTOYANT VITRE-GLASS CLEAN-3 EN1-750 ML','unité',1500,true,1900),
('superette','LAVE VITRE-SIMPLE CHOICE-1 LITRE','unité',1400,true,1910),
('superette','LIQUIDE DE VAISSELLE-PRIX MINI-POMME-1 LITRE','unité',1200,true,1920),
('superette','DESODORISANT GEL PARFUM-FLEURS BLANCHES','unité',900,true,1930),
('superette','DESODORISANT SPRAY-LAVANDE','unité',1300,true,1940),
('superette','DESODORISANT SPRAY-VANILLE','unité',1300,true,1950),
('superette','DESODORISANT SPRAY-MUGUET','unité',1300,true,1960),
('superette','DESODORISANT-FLEUR DE CERISIER','unité',1500,true,1970),
('superette','MADELAINE-EN BOITE','unité',900,true,1980),
('superette','MADELAINE-EN SACHETS','unité',500,true,1990),
('superette','GLACE FANICE-PETIT-150 ML','unité',500,true,2000),
('superette','GLACE FANICE-MOYEN-250 ML','unité',850,true,2010),
('superette','GLACE FANICE-GRAND-500 ML','unité',1500,true,2020),
('superette','FAN VANILLE','unité',100,true,2030),
('superette','FAN CHOCO','unité',200,true,2040),
('superette','YAOURT DOLAIT 500 G','unité',1200,true,2050),
('superette','YAOURT DOLAIT 200 G','unité',450,true,2060),
('superette','YAOURT DOLAIT 70 G','unité',150,true,2070),
('superette','YAOURT DOLAIT EN SACHET','unité',300,true,2080),
('superette','YAOURT ÔLE 300 ML','unité',400,true,2090),
('superette','YAOURT DÊGUÊ TROPICAL-1 LITRE','unité',2000,true,2100),
('superette','YAOURT DÊGUÊ TROPICAL-0,33 LITRE','unité',500,true,2110),
('superette','CIGARETTES-ORIS','unité',400,true,2120)
on conflict (categorie, nom) do update set
  prix_vente = excluded.prix_vente,
  ordre = excluded.ordre,
  actif = true;

-- ---------- Mouvements de stock (inventaire initial du 01/06/2026) ----------
-- Rejouable : on efface d'abord tout mouvement déjà posé sous ce ref.
delete from stock_movements where ref = 'inventaire-wezon-2026-06-01';

insert into stock_movements (station_id, categorie, produit, type, quantite, source, ref, note, date_mouvement)
select (select id from stations where nom = 'Beaurivage'), 'superette', v.nom, 'ajustement', v.stock,
  'inventaire', 'inventaire-wezon-2026-06-01', v.note, date '2026-06-01'
from (values
('BALLON MULTI-COLORE-CRF SACHETS 20 PCS',3,null),
('BALLON MULTI-COLORE-SACHETS 10 PCS',8,null),
('BALLON METAL 30 M MULTI-CRF-ACHAT 12 PCS',8,null),
('BOUGIE HAPPY BIRTHDAY CRF',3,null),
('20 BOUGIES+20 BOBECHES BLEU-CRF',3,null),
('20 BOUGIES+20 BOBECHES BLANC-CRF',3,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 0',5,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 1',0,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 2',4,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 3',4,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 4',2,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 5',1,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 6',2,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 7',5,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 8',3,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-CRF CHIFFRE 9',4,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 0',1,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 3',1,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 4',1,null),
('BOUGIE CHIFFRES HBD-AVEC BOBECHES-BELLE FRANCE CHIFFRE 9',1,null),
('ASSIETTES BLANCHES CARTON 23 CM CRF-SACHET 50 PCS',7,null),
('ASSIETTES PLASTIQUE GRAND FORMAT SACHET 50 PCS',0,null),
('SERVIETTE BLANCHE SACHET DE 100',3,null),
('ASSIETTES EN CARTON PIRATE CARTE AUX TRESORS-SACHET 6 PCS',25,null),
('ASSIETTES EN PAPIER PIRATE CARTE AUX TRESORS-SACHET 20 PCS',24,null),
('ASSIETTE 23 CM EN CARTON LICORNE-SACHET 6PCS',25,null),
('ASSIETTES EN PAPIER LICORNE-SACHET 20 PCS',6,null),
('ARACHIDE BOUTEILLE',4,null),
('AMUSE BOUCHE BOUTEILLE',4,null),
('CACAHUETE',7,null),
('ACADJOU BOUTEILLE',3,null),
('COCO RAPE',5,null),
('AKLUI',9,null),
('MIEL 1 LITRE',15,null),
('MIEL 0,5 LITRE',14,null),
('MIEL 0,3 LITRE',16,null),
('BISCUIT AUX RAISINS (MADELEINE)',5,null),
('CHIPS BANANE',104,null),
('NIDO-LAIT EN POUDRE',0,'Inventaire PDF: stock 2, périmé 31/03/2026, marqué "à retrancher" -> importé à 0'),
('SUCRE ROUX DADDY',3,null),
('FILTRE A CAFE BRUN N°4-CRF-BTEC-80',7,null),
('CAFE SOLUBLE-BOUTEILLE',1,null),
('VIN ROUGE-COTES DU RHÔNE',9,null),
('VIN MOUSSEUX-COMTE DE TALMON-DEMI-SEC',3,null),
('VIN MOUSSEUX-COMTE DE TALMON-BRUT',2,null),
('VIN MOUSSEUX-DEMI SEC BLANC-SIREBEAUPRE',0,null),
('VIN MOUSSEUX-JP,CHENET',4,null),
('VIN ROUGE-CHÂTEAU LA ROSE DE HAUT MOUSCHET',4,null),
('VIN ROUGE-CHÂTEAU TRAPAUD',3,null),
('VIN ROUGE-HAUT MEDEC',8,null),
('VIN ROUGE-SYRAH-GRANDE RESERVE-MAISON CASTEL',2,null),
('VIN ROUGE-BARON ROMEO',1,null),
('VIN ROUGE-PORTO ROCHEZ',7,null),
('VIN BLANC-PORTO ROCHEZ',5,null),
('VIN BLANC-ENTRE DEUX MERS',5,null),
('VIN BLANC-GEWURZTRAMINER',5,null),
('VIN BLANC-HAUTVALLON',1,null),
('VIN BLANC-BARON DE LESTAC',1,null),
('VIN BLANC-VUE 11°-FIN BOUQUET BTLVNC 75CL',1,null),
('VIN BLANC-COMTE DE SIRAC',1,null),
('VIN BLANC-LAVILLE PAVILLON',4,null),
('VIN ROSE-FRAMBOISE-OH MY FRAMB',7,null),
('VIN ROSE-PAMPLEMOUSSE-OH MY PAMP',6,null),
('VIN ROSE-SYRAH GRENACHE',2,null),
('VIN ROSE-CABERNET D''ANJOU',6,null),
('VIN ROSE-BORDERIVE',3,null),
('SPIRITUEUX VSOP BRANDY-OLIVIER DE BAUPREAU BTL VNC-70 CL',1,null),
('SPIRITUEUX 40% ARMAGNAC',5,null),
('VIN DE BORDEAUX MOELLEUX',1,null),
('VIN DE BORDEAUX-APPELLATION',1,null),
('VIN DE BORDEAUX-PAVILLON LA TOURELLE',5,null),
('VIN MALESAN-BORDEAUX',4,null),
('PASTIS-BELLE France',3,null),
('WILLIAM LAWSON''S-WHISKY',2,null),
('WILLIAM PEEL-WHISKY',9,null),
('LABEL 5-WHISKY',3,null),
('BLACK LABEL 70 CL-WHISKY',2,null),
('GIN BARMON''S',11,null),
('SPIRIT 24% LORD WYLL-WHISKY',3,null),
('BLENDED 40% WESTERLY-WHISKY',1,null),
('CAMPARI',5,null),
('MARTINI-BLANC',3,null),
('MARTINI-ROUGE',4,null),
('CREME DE CASSIS',10,null),
('EAU MINERALE-AQUABELLE-1,5 LITRE',4,null),
('EAU MINERALE-AQUABELLE-PACK DE 06',14,null),
('EAU MINERALE WEZON-EN VERRE JETTABLE',4,null),
('EAU MINERALE WEZON-EN VERRE JETTABLE-PACK DE 05',5,null),
('POSSOTOME GAZEIFIEE-1,5 LITRE',6,null),
('POSSOTOME GAZEIFIEE-PACK DE 06',1,null),
('POSSO CITRON-1 LITRE',7,null),
('POSSO CITRON-PACK DE 06',2,null),
('YOUKI COCKTAIL DE FRUIT 50 CL',4,null),
('YOUKI COCKTAIL DE FRUIT 50 CL-PACK DE 06',4,null),
('YOUKI PAMPLEMOUSSE-50 CL',6,null),
('YOUKI PAMPLEMOUSSE-50 CL-PACK DE 06',1,null),
('WORLD COLA',2,null),
('WORLD COLA-PACK DE 07',1,null),
('XXL 30 CL',12,null),
('NECTAR DE BAOBAB-AU LAIT DE COCO-GOLDEN ICE',9,null),
('NECTAR DE BAOBAB-AU LAIT DE COCO-GOLDEN ICE-PACK DE 06',3,null),
('NECTAR DE BAOBAB-GOLDEN ICE',5,null),
('NECTAR DE BAOBAB-GOLDEN ICE-PACK DE 06',4,null),
('PUR JUS D''ANANAS-GOLDEN ICE',5,null),
('PUR JUS D''ANANAS-GOLDEN ICE-PACK DE 06',4,null),
('JUS DE FRUIT-GOLDEN ICE-ANANAS,ORANGE,GINGEMBRE',2,null),
('JUS DE FRUIT-GOLDEN ICE-ANANAS,ORANGE,GINGEMBRE-PACK DE 06',6,null),
('JUS DE FRUIT-GOLDEN ICE-ANANAS,PASQUETTE',4,null),
('JUS DE FRUIT-GOLDEN ICE-ANANAS,PASQUETTE-PACK DE 06',7,null),
('JUS GOLDEN DETOX-GOLDEN ICE',2,null),
('JUS GOLDEN DETOX-GOLDEN ICE-PACK DE 06',20,null),
('BIERE BLONDE FORTE',1,null),
('RIZ PARFUME-DIVINE-5KG',5,null),
('RIZ PARFUME-DIVINE-5KG-PACK DE 05',2,null),
('RIZ PARFUME-DIVINE-1KG',37,null),
('MATANTI-PATE ALIMENTAIRE',80,null),
('SEL DE TABLE FIN',2,null),
('BICARBONATE DE SODIUM',19,null),
('FILM 2 EN 1-BELLE France',15,null),
('PAPIER CUISSON',2,null),
('SACHETS DE GLAÇONS',7,null),
('SACHETS-SACS DE CONGELATION-ZIP',2,null),
('VINAIGRE D''ALCOOL BLANC CHRISTAL',6,null),
('EPONGE BOULES-BOLLEN INOX',10,null),
('EPONGE CARRE-VAISSELLE-CFR',2,null),
('EPONGE CARRE-VAISSELLE-BELLE France',1,null),
('TAMPON SUREPONGE-BELLE France',6,null),
('SACS POUBELLES-PRIX MINI-30 LITRES',16,null),
('SACS POUBELLES-LIEN COULISSANT-CFR-100 LITRES',11,null),
('SACS POUBELLES-SPECIAL CONTAINER-CFR-120 LITRES',21,null),
('PAPIER TOILETTE DOUCHE-BELLE France',4,null),
('PATE DENTIFRICE-SIGNAL-EXTRA FRAICHEUR-75 ML',7,null),
('PATE DENTIFRICE-SIGNAL-INTERGAL COCO-75 ML',6,null),
('PATE DENTIFRICE-SIGNAL-SEL ROSE & CAMOMILLE-75 ML',8,null),
('PATE DENTIFRICE-SIGNAL-CRYSTAL GEL-75 ML',8,null),
('PATE DENTIFRICE-SIGNAL-INTERGAL BICARBONATE-75 ML',1,null),
('PATE DENTIFRICE-HALEINE PUR-75 ML',4,null),
('PATE DENTIFRICE-SIGNAL-INTERGAL CHARBON-75 ML',15,null),
('PATE DENTIFRICE-SIGNAL-INTERGAL INTERDENTAIRE-75 ML',11,null),
('PATE DENTIFRICE-SIGNAL-0-3 ANS-50 ML',10,null),
('PATE DENTIFRICE-SIGNAL-3-6 ANS-50 ML',1,null),
('BROSSE A DENT SIGNAL',1,null),
('RASOIRS-SIMPLE CHOICE JETABLE',8,null),
('MOUSSE A RASER-HOMME-PRIX MINI',3,null),
('TAMPON AVEC APPLICATEUR',4,null),
('SERVIETTE ULTRA',7,null),
('NANA SERVIETTE-HYGIENE',8,null),
('SAVON FANICO PETIT',28,null),
('SAVON FANICO MOYEN',3,null),
('BLOCS WC-LAVANDE',15,null),
('BLOCS WC-EXPERT FRESH OCEAN-3 IN 1',3,null),
('PASTILLES JAVEL',1,null),
('CREME A RECURER-EXPERT POWER CREAM-CITRON-750 ML',2,null),
('CREME A RECURER AVEC JAVEL-EXPERT POWER CREAM-ANANAS-750 ML',4,null),
('POUDRE A RECURER-AJAX JAVEL-750 G',7,null),
('EXPRESS-EXPERT DEBOUCHEUR GEL-CFR-13 TL-1 LITRE',4,null),
('NETTOYANT MENAGER-FRAICHEUR VERTE-VIGOR',2,null),
('DEODORANT NARTA-HOMME-INVIS MAX',6,null),
('DEODORANT NARTA-HOMME-PROTECTION 5',5,null),
('DEODORANT NARTA-COLOGNE',6,null),
('DEODORANT USHUAÏA',4,null),
('DEODORANT EBENE-EVASION TROPICAL',4,null),
('DEODORANT DOVE-INVISIBLE DRY',5,null),
('DEODORANT DOVE-ORIGINAL',3,null),
('DEODORANT DOVE-ADVANCED CARE',2,null),
('DEODORANT DOVE-ROLL ON STICK',4,null),
('DEODORANT L''OREAL-MEN EXPERT',6,null),
('DEODORANT BYPHASSE',6,null),
('RED FRUIT GOUGIE',8,null),
('GEL SHAMPOOING DOUCHE-CEDRE',5,null),
('GEL SHAMPOOING DOUCHE-AGRUMES',3,null),
('GEL DOUCHE-FRESH-3 IN 1',7,null),
('GEL SHAMPOOING-BAIN DOUCHE ENFANTS-KIDS',6,null),
('CREME DE DOUCHE-WITH VANILLE',5,null),
('CREME DE DOUCHE-WITH COCO',1,null),
('REPAIRING-LAIT CORPOREL REPARATEUR-CFR',10,null),
('LAIT DEMAQUILLANT-BELLE France-200 ML',2,null),
('LAIT CORP HYDRATANT-SIMPLE CHOICE',7,null),
('MIXA-LAIT DE BEAUTE-ANTI DESSECHEMENT-NUTRITION',5,null),
('MIXA-LAIT DE BEAUTE-ANTI DESSECHEMENT-BEAUTE',6,null),
('MIXA BEBE LAIT DE TOILETTE',4,null),
('COTON-DISQUES A DEMAQUILLER-PRIX MINI',4,null),
('COTON SACHET-200 G',2,null),
('PANSEMENTS UNIVERSELS',7,null),
('LIQUIDE VAISSELLE-PEAUX SENSIBLES-500 ML',3,null),
('ULTRA DEGRAISSANT-PEAUX SENSIBLES-BELLE France-500 ML',4,null),
('LIQUIDE DE VAISSELLE-DEGRAISSANT-CITRON-BELLE France-750 ML',2,null),
('LIQUIDE DE VAISSELLE-PRIX MINI-FRUITS ROUGE-500 ML',9,null),
('LIQUIDE DE VAISSELLE-PRIX MINI-CITRON-500 ML',5,null),
('NETTOYANT VITRE-GLASS CLEAN-3 EN1-750 ML',1,null),
('LAVE VITRE-SIMPLE CHOICE-1 LITRE',9,null),
('LIQUIDE DE VAISSELLE-PRIX MINI-POMME-1 LITRE',1,null),
('DESODORISANT GEL PARFUM-FLEURS BLANCHES',6,null),
('DESODORISANT SPRAY-LAVANDE',1,null),
('DESODORISANT SPRAY-VANILLE',6,null),
('DESODORISANT SPRAY-MUGUET',4,null),
('DESODORISANT-FLEUR DE CERISIER',11,null),
('MADELAINE-EN BOITE',10,null),
('MADELAINE-EN SACHETS',5,null),
('GLACE FANICE-PETIT-150 ML',7,null),
('GLACE FANICE-MOYEN-250 ML',10,null),
('GLACE FANICE-GRAND-500 ML',8,null),
('FAN VANILLE',11,null),
('FAN CHOCO',10,null),
('YAOURT DOLAIT 500 G',9,null),
('YAOURT DOLAIT 200 G',7,null),
('YAOURT DOLAIT 70 G',67,null),
('YAOURT DOLAIT EN SACHET',76,null),
('YAOURT ÔLE 300 ML',4,null),
('YAOURT DÊGUÊ TROPICAL-1 LITRE',5,null),
('YAOURT DÊGUÊ TROPICAL-0,33 LITRE',3,null),
('CIGARETTES-ORIS',22,null)
) as v(nom, stock, note);
